import "server-only";
import { slideExtension, type SlideMime } from "./limits";

/**
 * Storage keys for lesson attachments. Always generated by the server — the
 * browser is handed presigned POSTs pinned to these exact keys and never
 * learns them otherwise.
 *
 *   lesson-attachments/{lessonId}/{attachmentId}/original
 *   lesson-attachments/{lessonId}/{attachmentId}/p/{n}.webp   (n is 1-based;
 *                                                            .jpg for JPEG slides)
 */
export function attachmentStoragePrefix(lessonId: string, attachmentId: string): string {
  return `${lessonAttachmentsPrefix(lessonId)}${attachmentId}`;
}

/** Everything stored for one lesson's attachments (ends in "/"). */
export function lessonAttachmentsPrefix(lessonId: string): string {
  return `lesson-attachments/${lessonId}/`;
}

export function originalKey(storagePrefix: string): string {
  return `${storagePrefix}/original`;
}

export function pageKey(storagePrefix: string, page: number, mime: SlideMime): string {
  return `${storagePrefix}/p/${page}.${slideExtension(mime)}`;
}
