import "server-only";
import { and, asc, eq, inArray, isNull, sql } from "drizzle-orm";
import { db } from "../client";
import { lessonAttachments, lessons } from "../schema";
import type { AttachmentPageSize, LocalizedText } from "../schema";

export type LessonAttachmentRow = typeof lessonAttachments.$inferSelect;
export type AttachmentStatus = LessonAttachmentRow["status"];

export type LessonAttachmentInsert = {
  /** Generated by the caller: the storage prefix embeds it. */
  id: string;
  lessonId: string;
  title: LocalizedText;
  kind: "pdf" | "image";
  fileName: string;
  mimeType: string;
  sizeBytes: number;
  pageCount: number;
  pages: AttachmentPageSize[];
  slideMime: "image/webp" | "image/jpeg";
  storagePrefix: string;
  allowDownload: boolean;
  createdBy: string | null;
};

export type LessonAttachmentUpdate = {
  title?: LocalizedText;
  allowDownload?: boolean;
};

/**
 * Lesson attachments (slides under the video). Ordered per lesson by
 * order_index. Hard delete — the caller removes the stored objects first.
 */
export const lessonAttachmentsRepository = {
  /**
   * Append an attachment to its lesson's ordering.
   *
   * Runs under a row lock on the parent lesson so concurrent uploads (the
   * Studio uploads a queue in parallel) cannot collide on order_index or slip
   * past the per-lesson cap. Returns null when the lesson already holds
   * `maxPerLesson` attachments, or no longer exists (or is soft-deleted).
   */
  async create(input: LessonAttachmentInsert, opts: { maxPerLesson?: number } = {}) {
    return db.transaction(async (tx) => {
      const [lesson] = await tx
        .select({ id: lessons.id })
        .from(lessons)
        .where(and(eq(lessons.id, input.lessonId), isNull(lessons.deletedAt)))
        .for("update");
      if (!lesson) return null;

      const [{ count, next }] = await tx
        .select({
          count: sql<number>`count(*)::int`,
          next: sql<number>`coalesce(max(${lessonAttachments.orderIndex}) + 1, 0)::int`,
        })
        .from(lessonAttachments)
        .where(eq(lessonAttachments.lessonId, input.lessonId));
      if (opts.maxPerLesson != null && count >= opts.maxPerLesson) return null;

      const [row] = await tx
        .insert(lessonAttachments)
        .values({ ...input, orderIndex: next, status: "uploading" })
        .returning();
      return row;
    });
  },

  async findById(id: string) {
    const [row] = await db
      .select()
      .from(lessonAttachments)
      .where(eq(lessonAttachments.id, id))
      .limit(1);
    return row ?? null;
  },

  /** One lesson's attachments in display order (optionally only `ready`). */
  async listByLesson(lessonId: string, opts: { readyOnly?: boolean } = {}) {
    return db
      .select()
      .from(lessonAttachments)
      .where(
        opts.readyOnly
          ? and(eq(lessonAttachments.lessonId, lessonId), eq(lessonAttachments.status, "ready"))
          : eq(lessonAttachments.lessonId, lessonId),
      )
      .orderBy(asc(lessonAttachments.orderIndex), asc(lessonAttachments.createdAt));
  },

  /** Every attachment (any status) of several lessons, grouped by lesson id. */
  async listByLessons(lessonIds: string[]) {
    const grouped = new Map<string, LessonAttachmentRow[]>();
    if (lessonIds.length === 0) return grouped;
    const rows = await db
      .select()
      .from(lessonAttachments)
      .where(inArray(lessonAttachments.lessonId, lessonIds))
      .orderBy(asc(lessonAttachments.orderIndex), asc(lessonAttachments.createdAt));
    for (const row of rows) {
      const list = grouped.get(row.lessonId) ?? [];
      list.push(row);
      grouped.set(row.lessonId, list);
    }
    return grouped;
  },

  async countByLesson(lessonId: string) {
    const [{ count }] = await db
      .select({ count: sql<number>`count(*)::int` })
      .from(lessonAttachments)
      .where(eq(lessonAttachments.lessonId, lessonId));
    return count;
  },

  async update(id: string, patch: LessonAttachmentUpdate) {
    const [row] = await db
      .update(lessonAttachments)
      .set({ ...patch, updatedAt: sql`now()` })
      .where(eq(lessonAttachments.id, id))
      .returning();
    return row ?? null;
  },

  /** Move an attachment to a new upload status. */
  async setStatus(id: string, status: AttachmentStatus) {
    const [row] = await db
      .update(lessonAttachments)
      .set({ status, updatedAt: sql`now()` })
      .where(eq(lessonAttachments.id, id))
      .returning();
    return row ?? null;
  },

  /** Persist a new ordering. `ids` must be exactly the lesson's attachments. */
  async reorder(lessonId: string, ids: string[]) {
    await db.transaction(async (tx) => {
      for (let i = 0; i < ids.length; i++) {
        await tx
          .update(lessonAttachments)
          .set({ orderIndex: i, updatedAt: sql`now()` })
          .where(
            and(eq(lessonAttachments.id, ids[i]), eq(lessonAttachments.lessonId, lessonId)),
          );
      }
    });
  },

  /** Hard delete. Returns the removed row, or null when it was already gone. */
  async delete(id: string) {
    const [row] = await db
      .delete(lessonAttachments)
      .where(eq(lessonAttachments.id, id))
      .returning();
    return row ?? null;
  },
};
